services:
  - type: web
    name: phc-inventory-api
    runtime: node
    repo: https://github.com/deepbhagiya/phc-inventory-system
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
